# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m5Lv5XeGuf0A0z5ahviQa42Dz8PWBj6j
"""



from IPython.utils.text import columnize
#Listado de clientes
clientes = []
#Listado Lotes disponibles
lotesDisponibles = [
    ["[ ]","[ ]" ,"[ ]" , "[ ]", "[ ]"],
    ["[ ]","[ ]" ,"[ ]" , "[ ]", "[ ]"],
    ["[ ]","[ ]" ,"[ ]" , "[ ]", "[ ]"],
    ["[ ]","[ ]" ,"[ ]" , "[ ]", "[ ]"],
]
#Listado Detalle Lotes
lotesDetalle = [
    {"numero": 1, "tamaño": "5000 m²", "precio": "$2000 UF"},
    {"numero": 2, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 3, "tamaño": "5000 m²", "precio": "$2800 UF"},
    {"numero": 4, "tamaño": "5000 m²", "precio": "$1400 UF"},
    {"numero": 5, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 6, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 7, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 8, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 9, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 10, "tamaño": "5000 m²", "precio": "$1800 UF"},
    {"numero": 11, "tamaño": "5000 m²", "precio": "$1030 UF"},
    {"numero": 12, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 13, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 14, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 15, "tamaño": "5000 m²", "precio": "$4300 UF"},
    {"numero": 16, "tamaño": "5000 m²", "precio": "$8900 UF"},
    {"numero": 17, "tamaño": "5000 m²", "precio": "$950 UF"},
    {"numero": 18, "tamaño": "5000 m²", "precio": "$1400 UF"},
    {"numero": 19, "tamaño": "5000 m²", "precio": "$1500 UF"},
    {"numero": 20, "tamaño": "5000 m²", "precio": "$1500 UF"},
]

# Opción menú 1
def ver_disponibilidad_lotes():
  for i in range(len(lotesDisponibles)):
    for j in range(len(lotesDisponibles[i])):
      if lotesDisponibles[i][j]  == "[ ]":
                print("[ ]", end=" ")
      else:
                print("[X]", end=" ")
    print()


def seleccionar_lote():

#Datos Cliente
    print("--INGRESAR DATOS CLIENTE--")
    nombre = input("Nombre completo: ")
    rut = input("RUT: ")
    telefono = input("Ingrese su teléfono: ")
    email = input("Ingrese su email: ")

#Seleccion Lote
    fila = int(input("Ingrese la fila del lote: "))
    col = int(input("Ingrese la columna del lote: "))
    fila-=1
    col-=1

    if fila < 0 or fila >= len(lotesDisponibles) or col < 0 or col >= len(lotesDisponibles[0]):
        print("Coordenadas inválidas, porfavor intente nuevamente")
        return

    if lotesDisponibles[fila][col] == "[ ]":
        lotesDisponibles[fila][col] = "[X]"
        dataLote = {"fila": fila, "columna": col, "rut": rut, "nombre": nombre, "telefono": telefono, "email": email}
        clientes.append(dataLote)
        print("Lote seleccionado con éxito.")
    else:
        print("El lote seleccionado no está disponible.")


def mostrar_detalles_lote_seleccionado():
     if len(clientes) == 0:
        print("No hay clientes registrados.")
        return

        print("Lista de Clientes:")
        for cliente in clientes:
            rut, nombre, telefono, email = cliente
            print(f"Detalles del lote seleccionado:")
            print(f"Número: {lote['numero']}")
            print(f"Tamaño: {lote['tamaño']}")
            print(f"Precio: {lote['precio']} UF")
            print()

def mostrar_clientes():
    if len(clientes) == 0:
        print("No existen Clientes Registrados Aun.")
        return

        print("Clientes registrados:")
        for cliente in clientes:
            print(f"RUT: {cliente['rut']}")
            print(f"Nombre: {cliente['nombre']}")
            print(f"Teléfono: {cliente['telefono']}")
            print(f"Email: {cliente['email']}")
            print()


while (True):
    print("----- LoteosDUOC -----")
    print("1. Ver disponibilidad de lotes")
    print("2. Seleccionar un lote")
    print("3. Ver detalles del lote seleccionado")
    print("4. Ver clientes")
    print("5. Salir")

    opcion = int(input("Seleccione una opción: "))

    if opcion == 1:
        ver_disponibilidad_lotes()
    if opcion == 2:
        seleccionar_lote()
    if opcion == 3:
        mostrar_detalles_lote_seleccionado()
    if opcion == 4:
        mostrar_clientes()
    if opcion == 5:
        print("Adios, Muchas Gracias")
        break;
    if opcion < 1 | opcion > 5:
        print("Menú seleccionado no existe, intente nuevamente")



